# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Interninators

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_70782256750147eaa8f34f8ef795e58a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a0fc2ef52bd941d3a14f20325e56baad }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_70782256750147eaa8f34f8ef795e58a }}/alirafay/firebase-webapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Interninators'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_39b2eb9f37ca4c1792f7b33183d99408 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_70782256750147eaa8f34f8ef795e58a }}/alirafay/firebase-webapi:${{ github.sha }}'